### ISSUE TITLE
Found DiskReadViolation when strict mode enabled

### ISSUE THREAD

**Issue by jshaikql** [btkelly/gandalf#89]
In my sample app's onCreate() method i am trying to get gandalf instance as follows:

        this.gandalf = Gandalf.get()
        this.gandalf.shallIPass(this) 

then i found the following disk read violation and it's happening more frequently whenever i am coming back to app either from background or from back-stack.

Please find the stack trace when we enable strict mode policy in our app as follows:
`2019-11-01 14:44:54.701 17750-17750/com.sample.test.ui D/StrictMode: StrictMode policy violation; ~duration=119 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:251)
        at java.io.File.exists(File.java:815)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:605)
        at android.app.ContextImpl.ensurePrivateCacheDirExists(ContextImpl.java:601)
        at android.app.ContextImpl.getCacheDir(ContextImpl.java:694)
        at android.content.ContextWrapper.getCacheDir(ContextWrapper.java:269)
        at io.github.btkelly.gandalf.network.BootstrapApi.<init>(BootstrapApi.java:70)
        at io.github.btkelly.gandalf.Gandalf.shallIPass(Gandalf.java:140)
        at com.sample.test.ui.SplashActivity.onCreate(SplashActivity.kt:54)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by btkelly** [comment]
Thanks @jshaikql 👋I have a fix for this but I want to work on it a bit more as I don't love the solution. I'll get something up early next week.
